# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161211_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
